language: java
sudo: false
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
before_install:
- chmod +x gradlew
script: "./gradlew junitPlatformTest"
stages:
- test
- coverage
- name: snapshot
  if: branch != master
- name: release
  if: branch = master
jobs:
  include:
  - stage: coverage
    script:
    - "./gradlew check"
    - "bash <(curl -s https://codecov.io/bash)"
    jdk: oraclejdk8
  - stage: snapshot
    script: "./gradlew artifactoryPublish -Dsnapshot=true -Dbintray.user=$BINTRAY_USER
      -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8
  - stage: release
    script: "./gradlew bintrayUpload -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY
      -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/repositories/"
env:
  global:
  - secure: W4k9illxdk3xxavCb5UCaikX7Clv3K65hJcwKrS+dyGvGFyxC8cs6P59RykPGMGBD4LM6cjXbKdgoXMveBqAogkFdTDgcrmjwee+plgGZURzOO4ubOTk+LWBbzHeguUKYsrOF+nG3RfRvSnLm/pOlH65bB9IH2506L62mrjmzgM6ze0R99K0kgW4ysh/vB3mjumF/8RGETGmYzZkdDslPUGlFAnLoX/0lxGMcQ2i5WjoPKIu1NOb6fYD9ZYek9xNqUHA2yzpFkF87Z9Uhg5iqEpIGucLgdgh9BoFUE3cnZzhT8ByjTGuIapmSypDIbm3tsZeBlZ5IAzWuXmCyD3YbpfB/+/3enDVUBRGJOxj+sicuGN02EUyAOhOSLD9MZjAy8HOUSiJU9XwjafLqCy2Yvvgz6/wxCLCdCiPj3XpmoT8+35XWYFY46MVFQnKYOqsOJxM5FnWHOmY9bJih0636hnug+1lUQXbGQYyVndXIZf6ACU8ZNylylZi/b9UqIM1Vk9AVRtGaM2r1E+Y4V4xnBZkxqAm/7CTFoMGsuMqLpm5rxuF47YejmjhWhKw6oRBAXTGe35MVZXM+BIHgnfao+QC/lgZK4QFRj3TYJmTtDBp9emjrX2L3dOZM1aNOKACf2//E1zY/yn6LImMMD61161P0UvirDAKoXyzoLClnu8=
  - secure: oqg0b9UbSUHVpqHWmppUVQfeXk5MbisRMnETll0y0LOJr2VlrQ0xvNU9SAGGckh1t2cDAI6LF7eufm3/007acyNJ78tTzqwhq/wUPEjQlLdk9h83nNMvRg3J4GkwEpNq/bDJUrLHuSn99gP4bxh9EhK52IZ8EBneQ4H7ch7G610hDJLU5hVObNT1PFkuBf15y/6HzQvXB4MOXlbepGA2YmWf08Moq0Y016vIThuS6ZnmCRF+EQ0Y5fPw4uPD8u5rRIT6fNfPvJAE+eRiuI9ZvUee8gBVwgTen1dKQzmFkCl6/az5FcaPwuq9EM9ewGB5DHttUcoq8k5OE0aCiwYLOdS1h9V2Ss/b0Rd2sxaAuhluRQfuqqkpyUNY7QwGUVuqdL7LDYCfItxOyk5zPpzv4aOhc8MAwa5snZ3jhTDKcq+qd/I13oBZlBE8rTi7okVTWoRqI2JxyPesjKE30RyK+o0iibhjgfuFGw2CfX8vwBVs1ye9kCu8IGXuW3EwQ1f0tgvmP5T5P9OFmMmHe63fNunjqfZrsYKMh0By4pgQ2xoDHJg2xUIUY5VJ8hAVfchRQ82StFWyGAACAhk+EydwHCtCXhORnvmaZXrEKbsqmswd5jpk0mWucJWI7Mjz0mvwt/CXh206QjDxTTTa65NEuHHVKzZbE/C9KIihdIEhWgI=
  - secure: VX1fYehxL+9THYtyT+gQ9vmf45OTv21IcUVswEtLVgFlIp/rqYncmUKnkfk6Ss8i/RiAdsjt3earC3bhrXZzEVi0iSFiQ94h7i4Rdnwtmxu/esadbF+Wgz49zpn61klCqR6qp8T9M+iF4u0K3kQUEYa6CmYfp0gvhk3/2oPTTYvk3fn+26BTntFoFna8BG3QvdaziWBDen1lfYg0V4HLGHz462hN1/xgNy7lynvawuv5UDQi9KOv0Rpoei5GYPS8+RApR5MbXpRqc6l3dQ8i0kJk+ANq4wdBMUvj2V2HT6Z0o2kZqlLeiYIOPOjTJZpA9RMnMzTApFnCs8d+s7FsjHCOZyawf/m4MIp9k60xT1iyrXf8Na23uHaR8BrsYm/XtedQni8EhYy1Jr4wLvr19+kXMLEDydtOnKMLxfREDO8lHEwuzacH6ECn/fda8Dtdt2lU2ZRkzhe/LYbBBrVlbHvGEprteplDsYW2lGfiD2mUoseiSVyYfPX5vOcJjw6RBmgH6vkDwF6as0Y4milWK++Lh1hWEU2K1jh854hXj90D49P+GEtMmlU8gMS+YII51dcJyUlrCqpI18HugplhHvsWBzreGkRN7cuAfzjQa8Bi4HAohZnr2wRfb5Q/VCzxXDySQVC0JGObij5w6CV1tfIPqEejyxPhSEmEL+TGas4=
